version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    command: >
      bash -c
      "python3 manage.py migrate
      && gunicorn -w4 -b 0.0.0.0:5000 --log-level=debug --access-logfile error.log SE_Backend.wsgi:application"
    volumes:
      - ~/SE_ContestServicePlatform/SE_Backend:/code
      - static-volume:/code/static
    expose:
      - "5000"
    depends_on:
      - db
    networks:
      - web_network
      - db_network
  db:
    container_name: mysql
    image: mysql:latest
    volumes:
      - "~/contest_plus/mysql:/var/lib/mysql"
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - db_network
  nginx:
    container_name: nginx
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static-volume:/res
      - ~/SE_ContestServicePlatform/frontend/dist:/dist
      - ~/contest_plus/config/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network
      
networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge
    
volumes:
  static-volume: