# Generated by Django 3.1.3 on 2020-11-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=16)),
                ('userId', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=6)),
                ('sendTime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorName', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=64)),
                ('loginStatus', models.BooleanField()),
                ('checkStatus', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=64)),
                ('loginStatus', models.BooleanField()),
                ('qualificationStatus', models.CharField(max_length=16)),
                ('documentNumberNeeded', models.BooleanField()),
                ('documentNumber', models.BooleanField()),
                ('trueName', models.CharField(max_length=32)),
                ('birthTime', models.DateField()),
            ],
        ),
    ]
