# Generated by Django 3.1.3 on 2020-11-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('abstract', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField()),
                ('module', models.CharField(max_length=256)),
                ('sponsorId', models.IntegerField(default=0)),
                ('allowGroup', models.BooleanField(default=False)),
                ('maxGroupMember', models.IntegerField(default=1)),
                ('minGroupMember', models.IntegerField(default=1)),
                ('censorStatus', models.BooleanField(default=False)),
                ('applyStartTime', models.DateTimeField()),
                ('applyDeadline', models.DateTimeField()),
                ('contestStartTime', models.DateTimeField()),
                ('contestDeadline', models.DateTimeField()),
                ('reviewStartTime', models.DateTimeField()),
                ('reviewDeadline', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EmailCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=16)),
                ('userId', models.CharField(max_length=16)),
                ('code', models.CharField(max_length=8)),
                ('sendTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='single', max_length=16)),
                ('participantId', models.IntegerField(default=0)),
                ('targetContestId', models.IntegerField(default=0)),
                ('checkStatus', models.BooleanField(default=False)),
                ('completeStatus', models.BooleanField(default=False)),
                ('grade', models.IntegerField(default=0)),
                ('fullGrade', models.IntegerField(default=100)),
                ('awardTitle', models.CharField(max_length=256)),
                ('awardContent', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsorName', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=64)),
                ('emailVerifyStatus', models.BooleanField(default=False)),
                ('loginStatus', models.BooleanField(default=False)),
                ('checkStatus', models.CharField(max_length=64)),
                ('pubKey', models.CharField(blank=True, max_length=512)),
                ('priKey', models.CharField(blank=True, max_length=512)),
                ('jwt', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=64)),
                ('emailVerifyStatus', models.BooleanField(default=False)),
                ('loginStatus', models.BooleanField(default=False)),
                ('qualificationStatus', models.CharField(max_length=16)),
                ('documentNumberNeeded', models.BooleanField(default=False)),
                ('documentNumber', models.CharField(max_length=32)),
                ('trueName', models.CharField(max_length=32)),
                ('birthTime', models.DateField(blank=True, null=True)),
                ('pubKey', models.CharField(blank=True, max_length=512)),
                ('priKey', models.CharField(blank=True, max_length=512)),
                ('jwt', models.CharField(blank=True, max_length=512)),
            ],
        ),
    ]
