# Generated by Django 3.1.3 on 2020-12-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='censorString',
            field=models.CharField(default='', max_length=128),
        ),
    ]
