# Generated by Django 3.1.3 on 2020-11-11 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public', models.CharField(max_length=256)),
                ('private', models.IntegerField(max_length=256)),
                ('userType', models.CharField(max_length=16)),
                ('userId', models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='userId',
            field=models.IntegerField(max_length=16),
        ),
    ]
