# Generated by Django 3.1.3 on 2020-12-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ContestPlus', '0001_initial'),
    ]

    operations = [

    ]
