# Generated by Django 3.1.3 on 2020-11-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='maxGroupMember',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contest',
            name='minGroupMember',
            field=models.IntegerField(default=1),
        ),
    ]
