# Generated by Django 3.1.3 on 2020-11-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.AddField(
            model_name='contest',
            name='link',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(default='user', max_length=16),
        ),
    ]
