# Generated by Django 3.1.3 on 2020-12-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0002_auto_20201203_1234'),
    ]

    operations = [

    ]
