# Generated by Django 3.1.3 on 2020-12-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0002_auto_20201203_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128)),
                ('valid', models.BooleanField(default=True)),
                ('username', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='qualificationStatus',
        ),
    ]
