# Generated by Django 3.1.1 on 2020-11-16 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0002_auto_20201111_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RSA',
        ),
    ]
