# Generated by Django 3.1.3 on 2020-11-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0002_auto_20201119_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='single', max_length=16)),
                ('participantId', models.IntegerField(default=0)),
                ('targetContestId', models.IntegerField(default=0)),
                ('checkStatus', models.BooleanField(default=False)),
                ('completeStatus', models.BooleanField(default=False)),
                ('grade', models.IntegerField(default=0)),
                ('fullGrade', models.IntegerField(default=100)),
                ('awardTitle', models.CharField(max_length=256)),
                ('awardContent', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='contest',
            name='allowGroup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='censorStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contest',
            name='sponsorId',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='loginStatus',
            field=models.BooleanField(default=False),
        ),
    ]
