# Generated by Django 3.1.3 on 2020-11-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0002_auto_20201125_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documentNumberNeeded',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qualificationStatus',
            field=models.CharField(default=False, max_length=16),
        ),
    ]
