# Generated by Django 3.1.3 on 2020-11-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0002_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_id', models.IntegerField()),
                ('url', models.CharField(max_length=128)),
                ('hostType', models.CharField(default='none', max_length=16)),
                ('hostId', models.IntegerField()),
            ],
        ),
    ]
