# Generated by Django 3.1.3 on 2020-12-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ContestPlus', '0002_contest_counter_emailcode_group_invitationcode_notice_participation_picture_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('participantOnly', models.BooleanField(default=False)),
                ('sponsor', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('link', models.CharField(max_length=512)),
                ('file', models.CharField(max_length=512)),
            ],
        ),
    ]
