# Generated by Django 3.1.3 on 2020-11-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0003_auto_20201125_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='censorStatus',
            field=models.CharField(default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='qualificationStatus',
            field=models.CharField(default='guest', max_length=16),
        ),
    ]
