# Generated by Django 3.1.3 on 2020-12-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0003_participation_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='schoolNumber',
            new_name='studentNumber',
        ),
    ]
