# Generated by Django 3.1.1 on 2020-11-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0003_delete_rsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
