# Generated by Django 3.1.3 on 2020-12-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0003_auto_20201203_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthTime',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='documentNumber',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='priKey',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pubKey',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='trueName',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
