# Generated by Django 3.1.3 on 2020-11-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0003_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='thumb',
            field=models.CharField(blank=True, max_length=218),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
