# Generated by Django 3.1.3 on 2020-12-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0003_contest_counter_emailcode_group_invitationcode_notice_participation_picture_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='sponsor',
        ),
    ]
