# Generated by Django 3.1.3 on 2020-11-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0004_auto_20201127_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='thumb',
            field=models.CharField(blank=True, max_length=218, null=True),
        ),
    ]
