# Generated by Django 3.1.1 on 2020-11-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0004_auto_20201116_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailVerifyStatus',
            field=models.BooleanField(default=False),
        ),
    ]
