# Generated by Django 3.1.3 on 2020-12-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0004_auto_20201203_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='contestId',
            new_name='contest_id',
        ),
        migrations.AddField(
            model_name='notice',
            name='sponsor',
            field=models.IntegerField(default=0),
        ),
    ]
