# Generated by Django 3.1.3 on 2020-12-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0004_auto_20201209_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='publishResult',
            field=models.IntegerField(blank=True, default=False, null=True),
        ),
    ]
