# Generated by Django 3.1.3 on 2020-11-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0004_auto_20201125_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='awardContent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='participation',
            name='awardTitle',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='participation',
            name='checkStatus',
            field=models.CharField(default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='participation',
            name='completeStatus',
            field=models.CharField(default='competing', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='documentNumber',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='documentNumberNeeded',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='trueName',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
