# Generated by Django 3.1.3 on 2020-12-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0005_auto_20201127_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='censorString',
            field=models.CharField(default='', max_length=128),
        ),
    ]
