# Generated by Django 3.1.3 on 2020-12-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0005_contest_publishresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(default='guest', max_length=16),
        ),
    ]
