# Generated by Django 3.1.1 on 2020-11-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0005_user_emailverifystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcode',
            name='code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='sendTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
