# Generated by Django 3.1.1 on 2020-11-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0006_auto_20201116_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='documentNumber',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='documentNumberNeeded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='loginStatus',
            field=models.BooleanField(default=False),
        ),
    ]
