# Generated by Django 3.1.3 on 2020-12-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0007_participation_submission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='submission',
            new_name='submissionDir',
        ),
        migrations.AddField(
            model_name='participation',
            name='submissionName',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
