# Generated by Django 3.1.1 on 2020-11-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0007_auto_20201116_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthTime',
            field=models.DateField(blank=True, null=True),
        ),
    ]
