# Generated by Django 3.1.1 on 2020-11-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0008_auto_20201116_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('module', models.CharField(max_length=256)),
                ('sponserId', models.IntegerField()),
                ('allowGroup', models.BooleanField()),
                ('maxGroupMember', models.IntegerField()),
                ('minGroupMember', models.IntegerField()),
                ('censorStatus', models.BooleanField()),
                ('applyStartTime', models.DateTimeField()),
                ('applyDeadline', models.DateTimeField()),
                ('contestStartTime', models.DateTimeField()),
                ('contestDeadline', models.DateTimeField()),
                ('reviewStartTime', models.DateTimeField()),
                ('reviewDeadline', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='sponsor',
            name='emailVerifyStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailcode',
            name='userId',
            field=models.CharField(max_length=16),
        ),
    ]
