# Generated by Django 3.1.3 on 2020-11-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0008_auto_20201116_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='jwt',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='priKey',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='pubKey',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='jwt',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='priKey',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='user',
            name='pubKey',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
