# Generated by Django 3.1.3 on 2020-12-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0010_user_groupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groupCodeGenerateTime',
            field=models.IntegerField(default=0),
        ),
    ]
