# Generated by Django 3.1.3 on 2020-12-16 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0012_auto_20201214_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='awardContent',
            new_name='extraAward',
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='awardTitle',
            new_name='mainAward',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='fullGrade',
        ),
    ]
