# Generated by Django 3.1.3 on 2020-12-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0015_auto_20201219_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='verifyCode',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='participation',
            name='extraAward',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='participation',
            name='mainAward',
            field=models.CharField(default='', max_length=256),
        ),
    ]
