# Generated by Django 3.1.3 on 2020-12-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0016_auto_20201220_0315'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('fileDir', models.CharField(max_length=128)),
                ('fileName', models.CharField(max_length=128)),
                ('result', models.CharField(max_length=16)),
            ],
        ),
    ]
