# Generated by Django 3.1.3 on 2020-12-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0017_manualqualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualqualification',
            name='resultMessage',
            field=models.CharField(default='', max_length=256),
        ),
    ]
