# Generated by Django 3.1.3 on 2020-12-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0018_manualqualification_resultmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sessionId',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
