# Generated by Django 3.1.3 on 2020-12-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContestPlus', '0020_auto_20201224_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jwt',
            field=models.CharField(default='placeholder', max_length=512),
        ),
    ]
